import type { EvidenceBackedClaim, EvidenceSummary } from "@healthviewos/schema"
import { FileText, ShieldCheck } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"

function formatLabel(value: string) {
  return value
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ")
}

function formatDate(value?: string) {
  if (!value) return "Unknown"

  return new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "short",
    year: "numeric",
  }).format(new Date(value))
}

function EvidenceRow({ evidence }: { evidence: EvidenceSummary }) {
  return (
    <div className="rounded-xl border bg-background p-3">
      <div className="flex items-start gap-3">
        <div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-secondary text-secondary-foreground">
          <FileText className="size-4" aria-hidden="true" />
        </div>
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium">{evidence.artifactTitle}</p>
          <p className="mt-1 truncate text-xs text-muted-foreground">{evidence.sourceName}</p>
        </div>
      </div>
      <div className="mt-3 grid gap-2 text-xs text-muted-foreground">
        <div className="flex items-center justify-between gap-3">
          <span>Trust</span>
          <span className="font-medium text-foreground">{formatLabel(evidence.sourceTrust)}</span>
        </div>
        <div className="flex items-center justify-between gap-3">
          <span>Acquired</span>
          <span className="font-medium text-foreground">{formatDate(evidence.acquiredAt)}</span>
        </div>
        <div className="flex items-center justify-between gap-3">
          <span>Observed</span>
          <span className="font-medium text-foreground">{formatDate(evidence.observedAt)}</span>
        </div>
        <div className="flex items-center justify-between gap-3">
          <span>Method</span>
          <span className="font-medium text-foreground">{formatLabel(evidence.acquisitionMethod)}</span>
        </div>
      </div>
      {evidence.note ? (
        <p className="mt-3 text-sm leading-6 text-muted-foreground">{evidence.note}</p>
      ) : null}
    </div>
  )
}

export function EvidenceDialog({
  claim,
  onOpenChange,
  open,
}: {
  claim: EvidenceBackedClaim | null
  onOpenChange: (open: boolean) => void
  open: boolean
}) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[min(760px,calc(100dvh-2rem))] w-[calc(100vw-2rem)] max-w-2xl grid-rows-[auto_minmax(0,1fr)] gap-0 overflow-hidden p-0 sm:max-w-2xl">
        <DialogHeader className="border-b px-5 py-4 pr-12">
          <DialogTitle>{claim?.title ?? "Evidence"}</DialogTitle>
          <DialogDescription>
            Source context, confidence, and freshness for this HealthView OS claim.
          </DialogDescription>
        </DialogHeader>
        {claim ? (
          <div className="min-h-0 overflow-y-auto px-5 py-4">
            <div className="flex flex-col gap-4">
              <div className="rounded-xl bg-secondary p-4">
                <div className="flex items-start gap-3">
                  <div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-background text-foreground">
                    <ShieldCheck className="size-4" aria-hidden="true" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium">{claim.description}</p>
                    <p className="mt-2 text-xs leading-5 text-muted-foreground">
                      Generated by {claim.generatedBy}. Last updated {formatDate(claim.lastUpdatedAt)}.
                    </p>
                  </div>
                </div>
                <div className="mt-4 flex flex-wrap gap-2">
                  <Badge variant="secondary">Confidence: {formatLabel(claim.confidence)}</Badge>
                  <Badge variant="secondary">Freshness: {formatLabel(claim.freshness)}</Badge>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <h3 className="text-sm font-semibold">Evidence</h3>
                {claim.evidence.length > 0 ? (
                  claim.evidence.map((item) => <EvidenceRow evidence={item} key={item.id} />)
                ) : (
                  <div className="rounded-xl border bg-background p-3 text-sm text-muted-foreground">
                    No source artifact is linked yet. This signal should stay low confidence until evidence is imported.
                  </div>
                )}
              </div>
              {claim.recommendedAction ? (
                <Button variant="outline" className="w-full">
                  {claim.recommendedAction}
                </Button>
              ) : null}
            </div>
          </div>
        ) : null}
      </DialogContent>
    </Dialog>
  )
}
