import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const packageDir = resolve(scriptDir, "..")
const repoDir = resolve(packageDir, "../..")

const promptFiles = {
  endVoiceChatTool: "prompts/tools/end-voice-chat.md",
  controlAtlasViewTool: "prompts/tools/control-atlas-view.md",
  getAppContextTool: "prompts/tools/get-app-context.md",
  getRecordTool: "prompts/tools/get-record.md",
  getHealthContextTool: "prompts/tools/get-health-context.md",
  healthviewAgent: "prompts/healthview-agent.md",
  navigateTool: "prompts/tools/navigate.md",
  openPageTool: "prompts/tools/open-page.md",
  createRecordTool: "prompts/tools/create-record.md",
  runUiActionTool: "prompts/tools/run-ui-action.md",
  searchAppTool: "prompts/tools/search-app.md",
  searchAtlasTargetsTool: "prompts/tools/search-atlas-targets.md",
  searchRecordsTool: "prompts/tools/search-records.md",
  searchServicesTool: "prompts/tools/search-services.md",
  selectServiceResultTool: "prompts/tools/select-service-result.md",
  serverAgent: "prompts/server-agent.md",
  setChatOpenTool: "prompts/tools/set-chat-open.md",
  updateRecordTool: "prompts/tools/update-record.md",
  voiceSession: "prompts/voice-session.md",
}

const entries = await Promise.all(
  Object.entries(promptFiles).map(async ([name, relativePath]) => [
    name,
    await readFile(resolve(repoDir, relativePath), "utf8"),
  ]),
)

const templates = Object.fromEntries(entries)

const typeScriptOutput = `// Generated by packages/agent/scripts/generate-prompts.mjs. Edit files in /prompts instead.
export const promptTemplates = ${JSON.stringify(templates, null, 2)} as const
`

const javaScriptOutput = `// Generated by packages/agent/scripts/generate-prompts.mjs. Edit files in /prompts instead.
export const promptTemplates = ${JSON.stringify(templates, null, 2)}
`

const typeScriptOutputPath = resolve(packageDir, "src/generated/prompts.ts")
await mkdir(dirname(typeScriptOutputPath), { recursive: true })
await writeFile(typeScriptOutputPath, typeScriptOutput)

const javaScriptOutputPath = resolve(repoDir, "apps/web/api/generated-prompts.js")
await mkdir(dirname(javaScriptOutputPath), { recursive: true })
await writeFile(javaScriptOutputPath, javaScriptOutput)
